from investigator_app import db
from datetime import datetime


class Investigator(db.Model):
    __tablename__ = 'investigator_list'
    id = db.Column(db.Integer, primary_key=True)

    name = db.Column(db.String(255))
    furigana = db.Column(db.String(255))

    Player = db.Column(db.String(255))

    img = db.Column(db.String(255))

    job = db.Column(db.String(255))
    age = db.Column(db.String(255))
    sex = db.Column(db.String(255))
    height = db.Column(db.String(255))
    weight = db.Column(db.String(255))
    birthplace = db.Column(db.String(255))
    hair_color = db.Column(db.String(255))
    eye_color = db.Column(db.String(255))
    skin_color = db.Column(db.String(255))

    STR = db.Column(db.Integer)
    CON = db.Column(db.Integer)
    POW = db.Column(db.Integer)
    DEX = db.Column(db.Integer)
    APP = db.Column(db.Integer)
    SIZ = db.Column(db.Integer)
    INT = db.Column(db.Integer)
    EDU = db.Column(db.Integer)
    STR_add = db.Column(db.Integer)
    CON_add = db.Column(db.Integer)
    POW_add = db.Column(db.Integer)
    DEX_add = db.Column(db.Integer)
    APP_add = db.Column(db.Integer)
    SIZ_add = db.Column(db.Integer)
    INT_add = db.Column(db.Integer)
    EDU_add = db.Column(db.Integer)
    STR_tmp = db.Column(db.Integer)
    CON_tmp = db.Column(db.Integer)
    POW_tmp = db.Column(db.Integer)
    DEX_tmp = db.Column(db.Integer)
    APP_tmp = db.Column(db.Integer)
    SIZ_tmp = db.Column(db.Integer)
    INT_tmp = db.Column(db.Integer)
    EDU_tmp = db.Column(db.Integer)
    STR_sum = db.Column(db.Integer)
    CON_sum = db.Column(db.Integer)
    POW_sum = db.Column(db.Integer)
    DEX_sum = db.Column(db.Integer)
    APP_sum = db.Column(db.Integer)
    SIZ_sum = db.Column(db.Integer)
    INT_sum = db.Column(db.Integer)
    EDU_sum = db.Column(db.Integer)

    hp = db.Column(db.Integer)
    mp = db.Column(db.Integer)
    san = db.Column(db.Integer)
    ide = db.Column(db.Integer)
    luck = db.Column(db.Integer)
    knowledge = db.Column(db.Integer)
    hp_add = db.Column(db.Integer)
    mp_add = db.Column(db.Integer)
    san_add = db.Column(db.Integer)
    ide_add = db.Column(db.Integer)
    luck_add = db.Column(db.Integer)
    knowledge_add = db.Column(db.Integer)
    hp_tmp = db.Column(db.Integer)
    mp_tmp = db.Column(db.Integer)
    san_tmp = db.Column(db.Integer)
    ide_tmp = db.Column(db.Integer)
    luck_tmp = db.Column(db.Integer)
    knowledge_tmp = db.Column(db.Integer)
    hp_sum = db.Column(db.Integer)
    mp_sum = db.Column(db.Integer)
    san_sum = db.Column(db.Integer)
    ide_sum = db.Column(db.Integer)
    luck_sum = db.Column(db.Integer)
    knowledge_sum = db.Column(db.Integer)

    damage_bonus = db.Column(db.String(255))

    san_now = db.Column(db.Integer)

    skills = db.Column(db.JSON)
    sessions = db.Column(db.JSON)
    memo = db.Column(db.JSON)

    lost = db.Column(db.Boolean)
    
    iachara_link = db.Column(db.String)
    imgs_link = db.Column(db.String)

    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.now, onupdate=datetime.now)

class Session(db.Model):
    __tablename__ = 'session'
    id = db.Column(db.Integer, primary_key=True)
    senario_name = db.Column(db.String(255))
    date1 = db.Column(db.Date)
    date2 = db.Column(db.Date)
    date3 = db.Column(db.Date)
    date4 = db.Column(db.Date)
    date5 = db.Column(db.Date)
    date6 = db.Column(db.Date)
    date7 = db.Column(db.Date)
    date8 = db.Column(db.Date)
    date9 = db.Column(db.Date)
    date10 = db.Column(db.Date)

    KP = db.Column(db.String(255))
    KPC = db.Column(db.String(255))
    KPC_id = db.Column(db.Integer)
    SKP1 = db.Column(db.String(255))
    SKPC1 = db.Column(db.String(255))
    SKPC1_id = db.Column(db.Integer)
    SKP2 = db.Column(db.String(255))
    SKPC2 = db.Column(db.String(255))
    SKPC2_id = db.Column(db.Integer)
    SKP3 = db.Column(db.String(255))
    SKPC3 = db.Column(db.String(255))
    SKPC3_id = db.Column(db.Integer)

    PL1 = db.Column(db.String(255))
    PC1 = db.Column(db.String(255))
    PC1_id = db.Column(db.Integer)
    PL2 = db.Column(db.String(255))
    PC2 = db.Column(db.String(255))
    PC2_id = db.Column(db.Integer)
    PL3 = db.Column(db.String(255))
    PC3 = db.Column(db.String(255))
    PC3_id = db.Column(db.Integer)
    PL4 = db.Column(db.String(255))
    PC4 = db.Column(db.String(255))
    PC4_id = db.Column(db.Integer)
    PL5 = db.Column(db.String(255))
    PC5 = db.Column(db.String(255))
    PC5_id = db.Column(db.Integer)
    PL6 = db.Column(db.String(255))
    PC6 = db.Column(db.String(255))
    PC6_id = db.Column(db.Integer)
    PL7 = db.Column(db.String(255))
    PC7 = db.Column(db.String(255))
    PC7_id = db.Column(db.Integer)
    PL8 = db.Column(db.String(255))
    PC8 = db.Column(db.String(255))
    PC8_id = db.Column(db.Integer)
    PL9 = db.Column(db.String(255))
    PC9 = db.Column(db.String(255))
    PC9_id = db.Column(db.Integer)
    PL10 = db.Column(db.String(255))
    PC10 = db.Column(db.String(255))
    PC10_id = db.Column(db.Integer)

    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.now, onupdate=datetime.now)